### ISSUE TITLE
Prometheus Sink features/udpates

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-prometheus#3]
- [ ] Handle different metric types (gauge and counter)
- [ ] Handle different metric types in helper
- [ ] Make sink in JS with executable/cli (check StreamingFast sink)
- [ ] Try with timestamp label

TO-DO => add more
